# Generated by Django 5.1.6 on 2026-06-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='', max_length=200, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/logo/', verbose_name='Logo')),
                ('logradouro', models.CharField(blank=True, default='', max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, default='', max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('telefone2', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, default='', verbose_name='Site')),
                ('rodape_linha1', models.CharField(blank=True, default='', max_length=200, verbose_name='Rodapé Linha 1')),
                ('rodape_linha2', models.CharField(blank=True, default='', max_length=200, verbose_name='Rodapé Linha 2')),
                ('nome_representante', models.CharField(blank=True, default='', max_length=120, verbose_name='Nome do Representante Legal')),
                ('cargo_representante', models.CharField(blank=True, default='Diretor', max_length=50, verbose_name='Cargo do Representante')),
                ('foro_comarca', models.CharField(blank=True, default='', max_length=100, verbose_name='Foro / Comarca')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
    ]
