# Generated by Django 5.1.6 on 2026-06-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_historico', models.IntegerField(default=30, verbose_name='Peso Histórico Pagamento (%)')),
                ('peso_comprometimento', models.IntegerField(default=20, verbose_name='Peso Comprometimento Renda (%)')),
                ('peso_consulta_credito', models.IntegerField(default=25, verbose_name='Peso Consulta Crédito (%)')),
                ('peso_garantias', models.IntegerField(default=15, verbose_name='Peso Garantias (%)')),
                ('peso_perfil', models.IntegerField(default=10, verbose_name='Peso Perfil do Cliente (%)')),
                ('comprometimento_ideal', models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='Comprometimento Ideal (%)')),
                ('comprometimento_maximo', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Comprometimento Máximo (%)')),
                ('score_minimo_aprovacao', models.IntegerField(default=300, verbose_name='Score Mínimo p/ Aprovação')),
                ('score_atencao', models.IntegerField(default=500, verbose_name='Score de Atenção')),
                ('idade_minima_ideal', models.IntegerField(default=25, verbose_name='Idade Mínima Ideal')),
                ('idade_maxima_ideal', models.IntegerField(default=60, verbose_name='Idade Máxima Ideal')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Score',
                'verbose_name_plural': 'Configuração do Score',
            },
        ),
    ]
