# Generated by Django 5.1.6 on 2026-01-20 01:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoRecebivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('simulado', 'Simulado'), ('ativo', 'Ativo'), ('renegociado', 'Renegociado')], default='simulado', max_length=20)),
                ('taxa_desconto', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('data_ativacao', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato de Adiantamento de Recebíveis',
                'verbose_name_plural': 'Contratos de Adiantamento de Recebíveis',
            },
        ),
        migrations.CreateModel(
            name='ItemRecebivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cheque', 'Cheque'), ('nota_fiscal', 'Nota Fiscal'), ('cartao', 'Cartão')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='recebiveis.contratorecebivel')),
            ],
            options={
                'verbose_name': 'Item de Recebível',
                'verbose_name_plural': 'Itens de Recebíveis',
            },
        ),
    ]
