# Generated by Django 5.1.6 on 2026-01-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebiveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratorecebivel',
            name='contrato_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
