# Generated by Django 5.1.6 on 2026-01-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebiveis', '0002_alter_contratorecebivel_contrato_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecebivel',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrecebivel',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago')], default='aberto', max_length=10),
        ),
        migrations.AlterField(
            model_name='contratorecebivel',
            name='contrato_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contratorecebivel',
            name='status',
            field=models.CharField(choices=[('simulado', 'Simulado'), ('ativo', 'Ativo'), ('renegociado', 'Renegociado'), ('liquidado', 'Liquidado')], default='simulado', max_length=20),
        ),
    ]
