# Generated by Django 5.1.6 on 2026-06-21 14:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Conta Principal Itaú', max_length=100, verbose_name='Nome / Apelido')),
                ('banco', models.CharField(choices=[('001', 'Banco do Brasil'), ('033', 'Santander'), ('104', 'Caixa Econômica'), ('237', 'Bradesco'), ('341', 'Itaú'), ('077', 'Inter'), ('260', 'Nubank'), ('336', 'C6 Bank'), ('756', 'Sicoob'), ('748', 'Sicredi'), ('999', 'Outro')], max_length=5, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, default='', max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, default='', max_length=20, verbose_name='Conta')),
                ('tipo', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança')], default='CC', max_length=10, verbose_name='Tipo')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Inicial')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExtratoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('formato', models.CharField(choices=[('OFX', 'OFX'), ('CSV', 'CSV')], max_length=10, verbose_name='Formato')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('IMPORTADO', 'Importado'), ('CONCILIADO', 'Conciliado'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=15)),
                ('total_lancamentos', models.IntegerField(default=0, verbose_name='Total de Lançamentos')),
                ('total_conciliados', models.IntegerField(default=0, verbose_name='Conciliados')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Período Início')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='Período Fim')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='conciliacao.contabancaria')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extrato Importado',
                'verbose_name_plural': 'Extratos Importados',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição / Histórico')),
                ('documento', models.CharField(blank=True, default='', max_length=50, verbose_name='Documento / Nº')),
                ('tipo', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCILIADO', 'Conciliado (Auto)'), ('MANUAL', 'Conciliado (Manual)'), ('IGNORADO', 'Ignorado'), ('CRIADO', 'Lançamento Criado')], default='PENDENTE', max_length=15)),
                ('conciliado_em', models.DateTimeField(blank=True, null=True)),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to=settings.AUTH_USER_MODEL)),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='conciliacao.extratoimportado')),
                ('transacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_extrato', to='financeiro.transacao', verbose_name='Transação Vinculada')),
            ],
            options={
                'verbose_name': 'Lançamento do Extrato',
                'verbose_name_plural': 'Lançamentos do Extrato',
                'ordering': ['data', 'id'],
            },
        ),
    ]
