# Generated by Django 5.1.6 on 2026-06-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='banco',
            field=models.CharField(choices=[('001', 'Banco do Brasil'), ('033', 'Santander'), ('033', 'XP Investimentos'), ('104', 'Caixa Econômica'), ('237', 'Bradesco'), ('341', 'Itaú'), ('077', 'Inter'), ('260', 'Nubank'), ('336', 'C6 Bank'), ('756', 'Sicoob'), ('748', 'Sicredi'), ('999', 'Outro')], max_length=5, verbose_name='Banco'),
        ),
    ]
