# Generated by Django 5.1.6 on 2026-06-19 18:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_corrente', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito (Entrada)'), ('DEBITO', 'Débito (Saída)')], max_length=10)),
                ('origem', models.CharField(choices=[('EMPRESTIMO', 'Empréstimo Aprovado'), ('SAQUE', 'Saque em Espécie (Cód 05)'), ('DEPOSITO', 'Depósito em Espécie'), ('PAGAMENTO_PARCELA', 'Pagamento de Parcela'), ('TAXA', 'Cobrança de Taxa'), ('ANTECIPACAO', 'Antecipação de Recebíveis'), ('COMISSAO', 'Comissão de Parceiro')], default='SAQUE', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='contas.contacorrente')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.emprestimo')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.parcela')),
            ],
        ),
    ]
