# Generated by Django 5.1.6 on 2026-02-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='origem',
            field=models.CharField(choices=[('EMPRESTIMO', 'Empréstimo Aprovado'), ('SAQUE', 'Saque em Espécie (Cód 05)'), ('DEPOSITO', 'Depósito em Espécie'), ('PAGAMENTO_PARCELA', 'Pagamento de Parcela'), ('TAXA', 'Cobrança de Taxa'), ('ANTECIPACAO', 'Antecipação de Recebíveis')], default='SAQUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='tipo',
            field=models.CharField(choices=[('CREDITO', 'Crédito (Entrada)'), ('DEBITO', 'Débito (Saída)')], max_length=10),
        ),
    ]
