# Generated by Django 5.1.6 on 2026-06-27 17:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('financeiro', '0005_alter_tesouraria_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoconta',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='contacorrente',
            name='saldo_bloqueado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cheques em compensação — não disponível para saque', max_digits=12, verbose_name='Saldo Bloqueado'),
        ),
        migrations.AddField(
            model_name='movimentacaoconta',
            name='alinea',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma'), ('11', '11 - Sem fundos (1ª apresentação)'), ('12', '12 - Sem fundos (2ª apresentação)'), ('13', '13 - Conta encerrada'), ('20', '20 - Folha de cheque cancelada'), ('21', '21 - Contra-ordem / Sustação'), ('22', '22 - Divergência de assinatura'), ('25', '25 - Sem motivo de devolução'), ('28', '28 - Sustação judicial'), ('29', '29 - Falta de confirmação de recebimento'), ('31', '31 - Erro formal'), ('33', '33 - Divergência de endosso'), ('34', '34 - Cheque apresentado por estabelecimento não conveniado'), ('35', '35 - Cheque fraudado'), ('44', '44 - Cheque prescrito (+ de 6 meses)'), ('48', '48 - Cheque de valor superior ao estabelecido'), ('49', '49 - Remessa nula')], default='', max_length=5, verbose_name='Alínea Devolução'),
        ),
        migrations.AddField(
            model_name='movimentacaoconta',
            name='cheque_custodia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.chequecustodia'),
        ),
        migrations.AddField(
            model_name='movimentacaoconta',
            name='estornado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacaoconta',
            name='mov_estorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.movimentacaoconta'),
        ),
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='origem',
            field=models.CharField(choices=[('EMPRESTIMO', 'Empréstimo Aprovado'), ('SAQUE', 'Saque em Espécie'), ('DEPOSITO', 'Depósito em Espécie'), ('PAGAMENTO_PARCELA', 'Pagamento de Parcela'), ('TAXA', 'Cobrança de Taxa'), ('ANTECIPACAO', 'Antecipação de Recebíveis'), ('COMISSAO', 'Comissão de Parceiro'), ('CHEQUE_COMPENSACAO', 'Cheque em Compensação'), ('CHEQUE_COMPENSADO', 'Cheque Compensado'), ('CHEQUE_DEVOLVIDO', 'Cheque Devolvido (Estorno)')], default='SAQUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='tipo',
            field=models.CharField(choices=[('CREDITO', 'Crédito (Entrada)'), ('DEBITO', 'Débito (Saída)'), ('CREDITO_BLOQUEADO', 'Crédito Bloqueado (Cheque em Compensação)'), ('DESBLOQUEIO', 'Desbloqueio (Cheque Compensado)')], max_length=20),
        ),
    ]
