# Generated by Django 5.1.6 on 2026-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_movimentacaoconta_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='origem',
            field=models.CharField(choices=[('EMPRESTIMO', 'Empréstimo Aprovado'), ('SAQUE', 'Saque em Espécie (Cód 05)'), ('DEPOSITO', 'Depósito em Espécie'), ('PAGAMENTO_PARCELA', 'Pagamento de Parcela'), ('TAXA', 'Cobrança de Taxa'), ('ANTECIPACAO', 'Antecipação de Recebíveis'), ('COMISSAO', 'Comissão de Parceiro')], default='SAQUE', max_length=20),
        ),
    ]
