# Generated by Django 5.1.6 on 2026-01-24 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_data_nascimento'),
        ('emprestimos', '0004_emprestimo_juros_mora_mensal_percent_and_more'),
        ('recebiveis', '0003_itemrecebivel_data_pagamento_itemrecebivel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(verbose_name='Descrição do Evento')),
                ('tipo_contrato', models.CharField(default='GERAL', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobranca', to='emprestimos.emprestimo')),
                ('recebivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobranca', to='recebiveis.contratorecebivel')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Cobrança',
                'verbose_name_plural': 'Históricos de Cobrança',
                'ordering': ['-data_evento'],
            },
        ),
    ]
