# Generated by Django 5.1.6 on 2026-06-19 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('emprestimos', '0001_initial'),
        ('recebiveis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, help_text='Ex: Digite 20.00 para 20%', max_digits=5, verbose_name='Percentual (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('cliente_devedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_cobranca', to='clientes.cliente', verbose_name='Cliente Devedor')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carteira_profissional', to='clientes.cliente', verbose_name='Advogado/Cobrador')),
            ],
            options={
                'verbose_name': 'Regra de Split/Honorários',
                'verbose_name_plural': 'Regras de Split/Honorários',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(verbose_name='Descrição do Evento')),
                ('tipo_contrato', models.CharField(default='GERAL', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobranca', to='emprestimos.emprestimo')),
                ('recebivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobranca', to='recebiveis.contratorecebivel')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Cobrança',
                'verbose_name_plural': 'Históricos de Cobrança',
                'ordering': ['-data_evento'],
            },
        ),
    ]
