# Generated by Django 5.1.6 on 2026-02-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_contacorrente'),
        ('cobranca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, help_text='Ex: Digite 20.00 para 20%', max_digits=5, verbose_name='Percentual (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('cliente_devedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_cobranca', to='clientes.cliente', verbose_name='Cliente Devedor')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carteira_profissional', to='clientes.cliente', verbose_name='Advogado/Cobrador')),
            ],
            options={
                'verbose_name': 'Regra de Split/Honorários',
                'verbose_name_plural': 'Regras de Split/Honorários',
            },
        ),
    ]
