# Generated by Django 5.1.6 on 2026-06-21 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_telefone'),
        ('cobranca', '0001_initial'),
        ('emprestimos', '0002_politicacredito_alter_propostaemprestimo_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número Sequencial')),
                ('ano', models.IntegerField(verbose_name='Ano de Emissão')),
                ('numero_formatado', models.CharField(max_length=10, unique=True, verbose_name='Nº Correspondência')),
                ('qtd_parcelas_atraso', models.IntegerField(verbose_name='Parcelas em Atraso')),
                ('valor_total_atraso', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total em Atraso')),
                ('local_emissao', models.CharField(default='Rio de Janeiro', max_length=100, verbose_name='Local')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_cobranca', to='clientes.cliente')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_cobranca', to='emprestimos.emprestimo')),
            ],
            options={
                'verbose_name': 'Carta de Cobrança',
                'verbose_name_plural': 'Cartas de Cobrança',
                'ordering': ['-ano', '-numero'],
            },
        ),
    ]
