# Generated by Django 5.1.6 on 2026-06-24 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0002_cartacobranca'),
        ('emprestimos', '0005_propostaemprestimo_juros_mora_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARTORIO', 'Cartório / Protesto'), ('CORREIOS', 'Correios / Correspondência'), ('HONORARIOS', 'Honorários Advocatícios'), ('CUSTAS', 'Custas Judiciais'), ('OFICIAL', 'Oficial de Justiça'), ('DESLOCAMENTO', 'Deslocamento'), ('CONSULTA_CREDITO', 'Consulta de Crédito (SPC/Serasa)'), ('LIGACAO', 'Ligações Telefônicas'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Despesa')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='despesas_cobranca/%Y/%m/', verbose_name='Comprovante')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_cobranca', to='emprestimos.emprestimo', verbose_name='Contrato')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa de Cobrança',
                'verbose_name_plural': 'Despesas de Cobrança',
                'ordering': ['-data'],
            },
        ),
    ]
