# Generated by Django 5.1.6 on 2026-06-24 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('CAIXA', 'Caixa'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente'), ('DIRETOR', 'Diretor')], default='OPERACIONAL', max_length=20, verbose_name='Cargo / Nível'),
        ),
        migrations.CreateModel(
            name='PermissaoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('CLIENTES', 'Clientes'), ('ESTEIRA', 'Esteira de Crédito'), ('CONTRATOS', 'Gestão de Contratos'), ('FINANCEIRO', 'Fluxo de Caixa'), ('CONCILIACAO', 'Conciliação Bancária'), ('COBRANCA', 'Cobrança'), ('CONTAS_PAGAR', 'Contas a Pagar'), ('RECEBIVEIS', 'Recebíveis'), ('USUARIOS', 'Gestão de Usuários'), ('RELATORIOS', 'Relatórios')], max_length=20, verbose_name='Módulo')),
                ('nivel', models.CharField(choices=[('NENHUM', 'Sem Acesso'), ('VISUALIZAR', 'Visualizar'), ('OPERAR', 'Operar'), ('GERENCIAR', 'Gerenciar')], default='NENHUM', max_length=15, verbose_name='Nível de Acesso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Módulo',
                'verbose_name_plural': 'Permissões de Módulos',
                'ordering': ['modulo'],
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
