# Generated by Django 5.1.6 on 2026-06-19 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 01, 05', max_length=5, unique=True)),
                ('descricao', models.CharField(help_text='Ex: Despesas Gerais, Saque C/C', max_length=100)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=10)),
                ('exige_cliente', models.BooleanField(default=False, help_text='Se marcado, o sistema pedirá para selecionar um cliente.')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMPRESTIMO_SAIDA', 'Empréstimo (Saída)'), ('PAGAMENTO_ENTRADA', 'Pagamento Parc. (Entrada)'), ('ANTECIPACAO', 'Antecipação de Recebíveis'), ('DESPESA', 'Despesa Operacional'), ('APORTE', 'Aporte de Capital'), ('RETIRADA', 'Retirada de Lucro'), ('SAQUE_CC', 'Saque Conta Corrente (Cód 05)'), ('DEPOSITO_CC', 'Depósito Conta Corrente (Cód 06)'), ('OUTROS', 'Outros')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('codigo_autenticacao', models.CharField(blank=True, max_length=64, null=True)),
                ('codigo_operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.codigooperacao')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.emprestimo')),
                ('transacao_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.transacao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
