# Generated by Django 5.1.6 on 2026-01-19 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0004_emprestimo_juros_mora_mensal_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Aporte/Depósito'), ('SAQUE', 'Sangria/Saque'), ('EMPRESTIMO_SAIDA', 'Empréstimo (Saída)'), ('PAGAMENTO_ENTRADA', 'Pagamento de Parcela (Entrada)'), ('ESTORNO', 'Estorno')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='emprestimos.emprestimo')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data'],
            },
        ),
    ]
