# Generated by Django 5.1.6 on 2026-01-19 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='transacao_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='financeiro.transacao', verbose_name='Transação Original (ID Autenticação)'),
        ),
    ]
