# Generated by Django 5.1.6 on 2026-06-25 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('saldo_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo de Abertura')),
                ('aberto_em', models.DateTimeField(blank=True, null=True, verbose_name='Aberto em')),
                ('saldo_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Sistema')),
                ('saldo_conferido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Conferido')),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferença')),
                ('observacoes_fechamento', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('fechado_em', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('contagem_cedulas', models.JSONField(blank=True, default=dict, verbose_name='Contagem Cédulas')),
                ('contagem_moedas', models.JSONField(blank=True, default=dict, verbose_name='Contagem Moedas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data'],
            },
        ),
    ]
