# Generated by Django 5.1.6 on 2026-06-25 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_consultacredito_restricaocredito'),
        ('emprestimos', '0006_propostaemprestimo_descricao_debitos_and_more'),
        ('financeiro', '0002_caixa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='codigooperacao',
            options={'ordering': ['codigo']},
        ),
        migrations.AddField(
            model_name='codigooperacao',
            name='afeta_caixa_fisico',
            field=models.BooleanField(default=True, verbose_name='Afeta Caixa Físico?'),
        ),
        migrations.AddField(
            model_name='codigooperacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='aberto_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='contagem_cedulas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='contagem_moedas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='diferenca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='fechado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='observacoes_fechamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='saldo_abertura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='saldo_conferido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='saldo_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='codigooperacao',
            name='codigo',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='codigooperacao',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='codigooperacao',
            name='exige_cliente',
            field=models.BooleanField(default=False, verbose_name='Exige Cliente?'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('EMPRESTIMO_SAIDA', 'Empréstimo (Saída)'), ('PAGAMENTO_ENTRADA', 'Pagamento Parc. (Entrada)'), ('ANTECIPACAO', 'Antecipação de Recebíveis'), ('DESPESA', 'Despesa Operacional'), ('APORTE', 'Aporte de Capital'), ('RETIRADA', 'Retirada de Lucro'), ('SAQUE_CC', 'Saque Conta Corrente'), ('DEPOSITO_CC', 'Depósito Conta Corrente'), ('OUTROS', 'Outros')], max_length=30),
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('afetou_caixa_fisico', models.BooleanField(default=True, verbose_name='Afetou Caixa Físico')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_autenticacao', models.CharField(blank=True, default='', max_length=20)),
                ('estornado', models.BooleanField(default=False)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_estorno', models.CharField(blank=True, default='', max_length=200)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='financeiro.caixa')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('codigo_operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.codigooperacao')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.emprestimo')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos_caixa', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
