# Generated by Django 5.1.6 on 2026-06-27 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_consultacredito_restricaocredito'),
        ('emprestimos', '0008_chequegarantia'),
        ('financeiro', '0003_alter_caixa_options_alter_codigooperacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('numero_cheque', models.CharField(max_length=20, verbose_name='Nº Cheque')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('vencimento', models.DateField(verbose_name='Vencimento / Bom Para')),
                ('emitente', models.CharField(max_length=150, verbose_name='Emitente')),
                ('cpf_emitente', models.CharField(blank=True, default='', max_length=18, verbose_name='CPF Emitente')),
                ('status', models.CharField(choices=[('EM_CUSTODIA', 'Em Custódia'), ('ENVIADO_COMPENSACAO', 'Enviado p/ Compensação'), ('COMPENSADO', 'Compensado'), ('DEVOLVIDO', 'Devolvido')], default='EM_CUSTODIA', max_length=25)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data Entrada')),
                ('data_envio_compensacao', models.DateField(blank=True, null=True)),
                ('data_compensacao', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('motivo_devolucao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cheque_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.chequegarantia')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.emprestimo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('saldo_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesourarias_abertas', to=settings.AUTH_USER_MODEL)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesourarias_fechadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoTesouraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APORTE', 'Aporte / Entrada'), ('RETIRADA', 'Retirada'), ('ENVIO_CAIXA', 'Envio para Caixa'), ('RECEB_CAIXA', 'Recebimento do Caixa'), ('AJUSTE', 'Ajuste')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estornado', models.BooleanField(default=False)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('caixa_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.caixa')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos_tesouraria', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tesouraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='financeiro.tesouraria')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
