# Generated by Django 5.1.6 on 2026-01-24 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_lancamentofinanceiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='codigo_autenticacao',
            field=models.TextField(blank=True, help_text='Código hash para auditoria', null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='transacao_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='financeiro.transacao', verbose_name='Transação Original'),
        ),
    ]
