# Generated by Django 5.1.6 on 2026-02-01 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_alter_contratolog_options_alter_contratolog_acao_and_more'),
        ('financeiro', '0004_transacao_codigo_autenticacao_transacao_ip_origem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 01, 05', max_length=5, unique=True)),
                ('descricao', models.CharField(help_text='Ex: Despesas Gerais, Saque C/C', max_length=100)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=10)),
                ('exige_cliente', models.BooleanField(default=False, help_text='Se marcado, o sistema pedirá para selecionar um cliente.')),
            ],
        ),
        migrations.DeleteModel(
            name='LancamentoFinanceiro',
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={},
        ),
        migrations.AlterField(
            model_name='transacao',
            name='codigo_autenticacao',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='emprestimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.emprestimo'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('EMPRESTIMO_SAIDA', 'Empréstimo (Saída)'), ('PAGAMENTO_ENTRADA', 'Pagamento Parc. (Entrada)'), ('ANTECIPACAO', 'Antecipação de Recebíveis'), ('DESPESA', 'Despesa Operacional'), ('APORTE', 'Aporte de Capital'), ('RETIRADA', 'Retirada de Lucro'), ('SAQUE_CC', 'Saque Conta Corrente (Cód 05)'), ('OUTROS', 'Outros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='transacao_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.transacao'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='codigo_operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.codigooperacao'),
        ),
    ]
