# Generated by Django 5.1.6 on 2026-06-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_tesouraria_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='identificador',
            field=models.CharField(default='Caixa 1', help_text='Ex: Caixa 1, Caixa 2, Caixa Matriz', max_length=50, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
