# Generated by Django 5.1.6 on 2026-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_codigooperacao_delete_lancamentofinanceiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('EMPRESTIMO_SAIDA', 'Empréstimo (Saída)'), ('PAGAMENTO_ENTRADA', 'Pagamento Parc. (Entrada)'), ('ANTECIPACAO', 'Antecipação de Recebíveis'), ('DESPESA', 'Despesa Operacional'), ('APORTE', 'Aporte de Capital'), ('RETIRADA', 'Retirada de Lucro'), ('SAQUE_CC', 'Saque Conta Corrente (Cód 05)'), ('DEPOSITO_CC', 'Depósito Conta Corrente (Cód 06)'), ('OUTROS', 'Outros')], max_length=30),
        ),
    ]
