# Generated by Django 5.1.6 on 2026-06-19 18:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (xx) x xxxx-xxxx.', regex='^\\(\\d{2}\\)\\s\\d\\s\\d{4}-\\d{4}$')], verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF inválido. Use o formato xxx.xxx.xxx-xx.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('doc', models.CharField(blank=True, default='', max_length=30, verbose_name='Documento (RG/Doc)')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato xxxxx-xxx.', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, default='', max_length=120, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=80, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF')),
                ('percentual_comissao_padrao', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentual padrão de comissão para este cliente.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name=' % Comissão Padrão')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parceiro_padrao', models.ForeignKey(blank=True, help_text='Quem receberá comissão pelos contratos deste cliente automaticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to='clientes.cliente', verbose_name='Parceiro/Comissionado Padrão')),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito (Entrada)'), ('DEBITO', 'Débito (Saída)')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='clientes.cliente')),
            ],
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='clientes_cl_cpf_e6905f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome_completo'], name='clientes_cl_nome_co_05df70_idx'),
        ),
    ]
