# Generated by Django 6.0.1 on 2026-01-15 02:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (xx) x xxxx-xxxx.', regex='^\\(\\d{2}\\)\\s\\d\\s\\d{4}-\\d{4}$')], verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF inválido. Use o formato xxx.xxx.xxx-xx.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('doc', models.CharField(blank=True, default='', max_length=30, verbose_name='Documento (RG/Doc)')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato xxxxx-xxx.', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, default='', max_length=120, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=80, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['cpf'], name='clientes_cl_cpf_e6905f_idx'), models.Index(fields=['nome_completo'], name='clientes_cl_nome_co_05df70_idx')],
            },
        ),
    ]
