# Generated by Django 5.1.6 on 2026-06-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CNH_FRENTE', 'CNH / Identidade (Frente)'), ('CNH_VERSO', 'CNH / Identidade (Verso)'), ('ESTADO_CIVIL', 'Certidão de Estado Civil'), ('COMP_RENDA', 'Comprovante de Renda'), ('COMP_RESIDENCIA', 'Comprovante de Residência'), ('CONSULTA_CREDITO', 'Consulta Órgãos de Crédito')], max_length=20, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='documentos_clientes/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, default='', max_length=100, verbose_name='Descrição')),
                ('mes_referencia', models.IntegerField(blank=True, null=True, verbose_name='Mês Referência')),
                ('ano_referencia', models.IntegerField(blank=True, null=True, verbose_name='Ano Referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento do Cliente',
                'verbose_name_plural': 'Documentos dos Clientes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
