# Generated by Django 5.1.6 on 2026-02-23 14:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_contacorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parceiro_padrao',
            field=models.ForeignKey(blank=True, help_text='Quem receberá comissão pelos contratos deste cliente automaticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to='clientes.cliente', verbose_name='Parceiro/Comissionado Padrão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='percentual_comissao_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentual padrão de comissão para este cliente.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name=' % Comissão Padrão'),
        ),
    ]
