# Generated by Django 5.1.6 on 2026-06-22 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_documentocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável'), ('SEPARADO', 'Separado(a)')], default='', max_length=15, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='renda_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Renda Mensal (R$)'),
        ),
        migrations.CreateModel(
            name='BemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('CHACARA', 'Chácara'), ('SITIO', 'Sítio'), ('FAZENDA', 'Fazenda'), ('TERRENO', 'Terreno'), ('COMERCIAL', 'Imóvel Comercial'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=150, verbose_name='Descrição')),
                ('matricula', models.CharField(blank=True, default='', max_length=30, verbose_name='Nº Matrícula')),
                ('logradouro', models.CharField(blank=True, default='', max_length=120, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, default='', max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, default='', max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=80, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens_imoveis', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Bem Imóvel',
                'verbose_name_plural': 'Bens Imóveis',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BemMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMINHAO', 'Caminhão'), ('ONIBUS', 'Ônibus'), ('VAN', 'Van'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=150, verbose_name='Descrição / Modelo')),
                ('placa', models.CharField(blank=True, default='', max_length=10, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, default='', max_length=20, verbose_name='RENAVAM')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens_moveis', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Bem Móvel',
                'verbose_name_plural': 'Bens Móveis',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=100, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='bens_documentos/%Y/%m/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bem_imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.bemimovel')),
                ('bem_movel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.bemmovel')),
            ],
            options={
                'verbose_name': 'Documento do Bem',
                'verbose_name_plural': 'Documentos dos Bens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
