# Generated by Django 5.1.6 on 2026-06-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_estado_civil_cliente_profissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocliente',
            name='renda_bruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Renda Bruta'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='renda_liquida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Renda Líquida'),
        ),
    ]
