# Generated by Django 5.1.6 on 2026-06-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_documentocliente_renda_bruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=120, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='outros_rendimentos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Outros Rendimentos (R$)'),
        ),
    ]
