# Generated by Django 5.1.6 on 2026-06-24 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_email_cliente_outros_rendimentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NADA_CONSTA', 'Nada Consta'), ('ALERTA', 'Alerta'), ('COM_RESTRICAO', 'Com Restrições')], max_length=15, verbose_name='Resultado')),
                ('data_consulta', models.DateField(auto_now_add=True, verbose_name='Data da Consulta')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_credito', to='clientes.cliente')),
                ('documento', models.ForeignKey(blank=True, help_text='Documento de consulta vinculado (upload do PDF/imagem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_credito_vinculada', to='clientes.documentocliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de Crédito',
                'verbose_name_plural': 'Consultas de Crédito',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RestricaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_credor', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ do Credor')),
                ('nome_credor', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome da Empresa')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor (R$)')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes', to='clientes.consultacredito')),
            ],
            options={
                'verbose_name': 'Restrição',
                'verbose_name_plural': 'Restrições',
                'ordering': ['-valor'],
            },
        ),
    ]
