# Generated by Django 6.0.1 on 2026-01-15 02:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.CharField(db_index=True, max_length=20, unique=True)),
                ('valor_emprestado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('qtd_parcelas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)])),
                ('taxa_juros_mensal', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('primeiro_vencimento', models.DateField()),
                ('valor_parcela_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_contrato', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ajuste_arredondamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ATRASADO', 'Atrasado'), ('QUITADO', 'Quitado')], default='ATIVO', max_length=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga')], default='ABERTA', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='emprestimos.emprestimo')),
            ],
            options={
                'ordering': ['vencimento', 'numero'],
            },
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['codigo_contrato'], name='emprestimos_codigo__928c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['status'], name='emprestimos_status_f19e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['status', 'vencimento'], name='emprestimos_status_942a2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('emprestimo', 'numero')},
        ),
    ]
