# Generated by Django 5.1.6 on 2026-06-19 18:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.CharField(db_index=True, max_length=20, unique=True)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name=' % Comissão')),
                ('valor_emprestado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('qtd_parcelas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)])),
                ('taxa_juros_mensal', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('primeiro_vencimento', models.DateField()),
                ('valor_parcela_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_contrato', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ajuste_arredondamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ATRASADO', 'Atrasado'), ('QUITADO', 'Quitado'), ('RENEGOCIADO', 'Renegociado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tem_multa_atraso', models.BooleanField(default=True)),
                ('multa_atraso_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('juros_mora_mensal_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=120, null=True)),
                ('observacao_cancelamento', models.TextField(blank=True, null=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_cancelados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='clientes.cliente')),
                ('contrato_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='emprestimos.emprestimo')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_parceiro', to='clientes.cliente', verbose_name='Parceiro / Recebedor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContratoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('PAGO', 'Pago'), ('RENEGOCIADO', 'Renegociado'), ('CANCELADO', 'Cancelado'), ('REABERTO', 'Reaberto')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emprestimos.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('LIQUIDADA_RENEGOCIACAO', 'Liquidada por renegociação'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=40)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='emprestimos.emprestimo')),
            ],
            options={
                'ordering': ['vencimento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PropostaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtd_parcelas', models.IntegerField()),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('primeiro_vencimento', models.DateField()),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name=' % Comissão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Análise'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações do vendedor')),
                ('parecer_analise', models.TextField(blank=True, help_text='Justificativa da aprovação/reprovação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='clientes.cliente')),
                ('emprestimo_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.emprestimo')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_parceiro', to='clientes.cliente', verbose_name='Parceiro Indicador')),
                ('usuario_aprovador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_analisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['codigo_contrato'], name='emprestimos_codigo__928c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['status'], name='emprestimos_status_f19e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['status', 'vencimento'], name='emprestimos_status_942a2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('emprestimo', 'numero')},
        ),
    ]
