# Generated by Django 5.1.6 on 2026-01-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='contrato_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='emprestimos.emprestimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ATRASADO', 'Atrasado'), ('QUITADO', 'Quitado'), ('RENEGOCIADO', 'Renegociado')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('LIQUIDADA_RENEGOCIACAO', 'Liquidada por renegociação')], default='ABERTA', max_length=40),
        ),
    ]
