# Generated by Django 5.1.6 on 2026-06-19 19:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Padrão', max_length=100, verbose_name='Nome da Política')),
                ('ativo', models.BooleanField(default=True)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=12, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12, verbose_name='Valor Máximo')),
                ('prazo_maximo_meses', models.IntegerField(default=36, verbose_name='Prazo Máximo (meses)')),
                ('taxa_minima', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Taxa Mínima (%)')),
                ('taxa_maxima', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Taxa Máxima (%)')),
                ('score_minimo_aprovacao', models.CharField(default='Neutro', help_text='Bom Pagador, Neutro, Risco Médio, etc.', max_length=30, verbose_name='Score Mínimo')),
                ('max_contratos_ativos', models.IntegerField(default=3, verbose_name='Máx. Contratos Ativos Simultâneos')),
                ('permite_inadimplente', models.BooleanField(default=False, verbose_name='Permitir proposta de inadimplente?')),
                ('valor_max_sem_comite', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Acima deste valor, a proposta vai automaticamente pro Comitê.', max_digits=12, verbose_name='Valor Máx. sem Comitê')),
            ],
            options={
                'verbose_name': 'Política de Crédito',
                'verbose_name_plural': 'Políticas de Crédito',
            },
        ),
        migrations.AlterField(
            model_name='propostaemprestimo',
            name='status',
            field=models.CharField(choices=[('CAPTACAO', 'Captação'), ('DOCUMENTACAO', 'Análise Documental'), ('ANALISE_CREDITO', 'Análise de Crédito'), ('COMITE', 'Comitê'), ('FORMALIZACAO', 'Formalização'), ('LIBERACAO', 'Liberação'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente (Legado)')], default='CAPTACAO', max_length=20),
        ),
        migrations.CreateModel(
            name='EtapaProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('CAPTACAO', 'Captação'), ('DOCUMENTACAO', 'Análise Documental'), ('ANALISE_CREDITO', 'Análise de Crédito'), ('COMITE', 'Comitê'), ('FORMALIZACAO', 'Formalização'), ('LIBERACAO', 'Liberação')], max_length=20)),
                ('resultado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('DEVOLVIDO', 'Devolvido'), ('NEGADO', 'Negado')], default='PENDENTE', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('parecer', models.TextField(blank=True, default='', verbose_name='Parecer / Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='emprestimos.propostaemprestimo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa da Proposta',
                'verbose_name_plural': 'Etapas das Propostas',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório?')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído?')),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etapa_proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='emprestimos.etapaproposta')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['-obrigatorio', 'descricao'],
            },
        ),
    ]
