# Generated by Django 5.1.6 on 2026-06-21 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_politicacredito_alter_propostaemprestimo_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido')], max_length=15, verbose_name='Decisão')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Ressalvas aceitas pelo votante (ex: comprovante de renda desatualizado)', verbose_name='Observações')),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_comite', to='emprestimos.propostaemprestimo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_comite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto do Comitê',
                'verbose_name_plural': 'Votos do Comitê',
                'ordering': ['-data_voto'],
                'unique_together': {('proposta', 'usuario')},
            },
        ),
    ]
