# Generated by Django 5.1.6 on 2026-01-15 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_emprestimo_contrato_origem_alter_emprestimo_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='observacao_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ATRASADO', 'Atrasado'), ('QUITADO', 'Quitado'), ('RENEGOCIADO', 'Renegociado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('LIQUIDADA_RENEGOCIACAO', 'Liquidada por renegociação'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=40),
        ),
        migrations.CreateModel(
            name='ContratoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('PAGO', 'Pagamento'), ('RENEGOCIADO', 'Renegociado'), ('CANCELADO', 'Cancelado'), ('REABERTO', 'Reaberto')], max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emprestimos.emprestimo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
