# Generated by Django 5.1.6 on 2026-06-21 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_votocomite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoFormalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número Sequencial')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('numero_formatado', models.CharField(max_length=20, unique=True, verbose_name='Nº Contrato')),
                ('contrato_emitido', models.BooleanField(default=False, verbose_name='Contrato Emitido')),
                ('contrato_emitido_em', models.DateTimeField(blank=True, null=True)),
                ('promissoria_emitida', models.BooleanField(default=False, verbose_name='Nota Promissória Emitida')),
                ('promissoria_emitida_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_cliente', models.BooleanField(default=False, verbose_name='Assinado pelo Cliente')),
                ('assinado_empresa', models.BooleanField(default=False, verbose_name='Assinado pela Empresa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_formal', to='emprestimos.propostaemprestimo')),
            ],
            options={
                'verbose_name': 'Contrato Formalizado',
                'verbose_name_plural': 'Contratos Formalizados',
                'ordering': ['-ano', '-numero'],
            },
        ),
    ]
