# Generated by Django 5.1.6 on 2026-01-16 00:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_emprestimo_cancelado_em_emprestimo_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='juros_mora_mensal_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))]),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='multa_atraso_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))]),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='tem_multa_atraso',
            field=models.BooleanField(default=True),
        ),
    ]
