# Generated by Django 5.1.6 on 2026-06-22 14:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_estado_civil_cliente_profissao_and_more'),
        ('emprestimos', '0004_contratoformalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaemprestimo',
            name='juros_mora_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Juros de Mora (% a.m.)'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='multa_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Multa (%)'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='tem_juros_mora',
            field=models.BooleanField(default=True, verbose_name='Aplicar Juros de Mora?'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='tem_multa',
            field=models.BooleanField(default=True, verbose_name='Aplicar Multa por Atraso?'),
        ),
        migrations.CreateModel(
            name='GarantiaProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CHEQUE', 'Cheque'), ('AVALISTA', 'Avalista'), ('BEM_MOVEL', 'Bem Móvel (Veículo)'), ('BEM_IMOVEL', 'Bem Imóvel')], max_length=15, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('cheque_banco', models.CharField(blank=True, default='', max_length=50, verbose_name='Banco')),
                ('cheque_numero', models.CharField(blank=True, default='', max_length=30, verbose_name='Nº Cheque')),
                ('cheque_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Cheque')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avalista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_avalista', to='clientes.cliente', verbose_name='Avalista')),
                ('bem_imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_proposta', to='clientes.bemimovel')),
                ('bem_movel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_proposta', to='clientes.bemmovel')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='emprestimos.propostaemprestimo')),
            ],
            options={
                'verbose_name': 'Garantia da Proposta',
                'verbose_name_plural': 'Garantias das Propostas',
                'ordering': ['tipo'],
            },
        ),
    ]
