# Generated by Django 5.1.6 on 2026-01-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_emprestimo_juros_mora_mensal_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratolog',
            options={},
        ),
        migrations.AlterField(
            model_name='contratolog',
            name='acao',
            field=models.CharField(choices=[('CRIADO', 'Criado'), ('PAGO', 'Pago'), ('RENEGOCIADO', 'Renegociado'), ('CANCELADO', 'Cancelado'), ('REABERTO', 'Reaberto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contratolog',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contratolog',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
