# Generated by Django 5.1.6 on 2026-02-19 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_contacorrente'),
        ('emprestimos', '0005_alter_contratolog_options_alter_contratolog_acao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_parceiro', to='clientes.cliente', verbose_name='Parceiro / Recebedor'),
        ),
    ]
