# Generated by Django 5.1.6 on 2026-06-25 21:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_propostaemprestimo_juros_mora_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaemprestimo',
            name='descricao_debitos',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição Débitos Extras'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='finalidade',
            field=models.CharField(choices=[('CREDITO_PESSOAL', 'Crédito Pessoal'), ('CAPITAL_GIRO', 'Capital de Giro'), ('FINANCIAMENTO', 'Financiamento'), ('REFINANCIAMENTO', 'Refinanciamento'), ('RENEGOCIACAO', 'Renegociação'), ('OUTRO', 'Outro')], default='CREDITO_PESSOAL', max_length=20, verbose_name='Finalidade'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='iof_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.38'), max_digits=5, verbose_name='IOF Adicional (%)'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='iof_aliquota',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0082'), help_text='IOF diário padrão: 0,0082% a.d. + 0,38% adicional', max_digits=6, verbose_name='Alíquota IOF (%)'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='tem_iof',
            field=models.BooleanField(default=True, verbose_name='Cobrar IOF?'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total do contrato = solicitado + IOF + extras', max_digits=12, null=True, verbose_name='Valor Bruto (R$)'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='valor_debitos_extras',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Débitos Extras (R$)'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='valor_iof',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor IOF (R$)'),
        ),
    ]
