# Generated by Django 5.1.6 on 2026-02-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_contacorrente'),
        ('emprestimos', '0006_emprestimo_parceiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtd_parcelas', models.IntegerField()),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('primeiro_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Análise'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações do vendedor')),
                ('parecer_analise', models.TextField(blank=True, help_text='Justificativa da aprovação/reprovação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='clientes.cliente')),
                ('emprestimo_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emprestimos.emprestimo')),
                ('usuario_aprovador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_analisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
