# Generated by Django 5.1.6 on 2026-06-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0006_propostaemprestimo_descricao_debitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaemprestimo',
            name='score_calculado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score de Crédito'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='score_detalhamento',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalhamento Score'),
        ),
    ]
