# Generated by Django 5.1.6 on 2026-06-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0007_propostaemprestimo_score_calculado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('conta_corrente', models.CharField(max_length=20, verbose_name='Conta Corrente')),
                ('numero_cheque', models.CharField(max_length=20, verbose_name='Nº Cheque')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('emitente', models.CharField(max_length=150, verbose_name='Emitente')),
                ('cpf_emitente', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF Emitente')),
                ('conferido', models.BooleanField(default=False, verbose_name='Conferido?')),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_conferidos', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques_garantia', to='emprestimos.propostaemprestimo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque de Garantia',
                'verbose_name_plural': 'Cheques de Garantia',
                'ordering': ['vencimento'],
            },
        ),
    ]
