# Generated by Django 5.1.6 on 2026-02-23 14:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_parceiro_padrao_and_more'),
        ('emprestimos', '0007_propostaemprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name=' % Comissão'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_parceiro', to='clientes.cliente', verbose_name='Parceiro Indicador'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name=' % Comissão'),
        ),
    ]
