# Generated by Django 5.1.6 on 2026-06-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0008_chequegarantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaemprestimo',
            name='contrato_renegociado',
            field=models.ForeignKey(blank=True, help_text='Contrato original sendo renegociado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_renegociacao', to='emprestimos.emprestimo'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='valor_divida_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo devedor + multa + juros do contrato original', max_digits=12, null=True, verbose_name='Valor Dívida Original'),
        ),
        migrations.AddField(
            model_name='propostaemprestimo',
            name='valor_entrada_renegociacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Entrada na Renegociação'),
        ),
        migrations.AlterField(
            model_name='propostaemprestimo',
            name='finalidade',
            field=models.CharField(choices=[('CREDITO_PESSOAL', 'Crédito Pessoal'), ('CAPITAL_GIRO', 'Capital de Giro'), ('FINANCIAMENTO', 'Financiamento'), ('REFINANCIAMENTO', 'Refinanciamento'), ('RENEGOCIACAO', 'Renegociação'), ('ANTECIPACAO_RECEBIVEIS', 'Antecipação de Recebíveis'), ('OUTRO', 'Outro')], default='CREDITO_PESSOAL', max_length=25, verbose_name='Finalidade'),
        ),
    ]
