# Generated by Django 5.1.6 on 2026-06-21 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Nome / Descrição')),
                ('tipo_despesa', models.CharField(choices=[('ALUGUEL', 'Aluguel'), ('SALARIOS', 'Salários'), ('IMPOSTOS', 'Impostos'), ('AGUA', 'Água'), ('ENERGIA', 'Energia'), ('INTERNET', 'Internet'), ('TELEFONE', 'Telefone'), ('DESP_JUDICIAIS', 'Despesas Judiciais'), ('MULTAS', 'Multas'), ('TAXAS', 'Taxas'), ('MATERIAL', 'Material de Escritório'), ('MANUTENCAO', 'Manutenção'), ('TRANSPORTE', 'Transporte'), ('SEGUROS', 'Seguros'), ('CONTABILIDADE', 'Contabilidade'), ('MARKETING', 'Marketing'), ('SOFTWARE', 'Software / Assinaturas'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('fatura', models.FileField(blank=True, null=True, upload_to='contas_pagar/faturas/%Y/%m/', verbose_name='Fatura / Boleto')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADA', 'Aprovada para Pagamento'), ('PAGA', 'Paga'), ('NEGADA', 'Negada'), ('DEVOLVIDA', 'Devolvida para Correção')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa (negação/devolução)')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='contas_pagar/comprovantes/%Y/%m/', verbose_name='Comprovante de Pagamento')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagas', to=settings.AUTH_USER_MODEL, verbose_name='Pago por')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['vencimento'],
            },
        ),
    ]
